<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create multiple test users
        $users = [];
        for ($i = 1; $i <= 10; $i++) {
            $users[] = User::firstOrCreate(
                ['email' => "user{$i}@bookshare.de"],
                [
                    'name' => "Benutzer {$i}",
                    'password' => bcrypt('password123'),
                ]
            );
        }

        $books = [
            // ===== FANTASY =====
            [
                'title' => 'Der Herr der Ringe: Die Gefährten',
                'author' => 'J.R.R. Tolkien',
                'isbn' => '9783608938041',
                'description' => 'Ein episches Fantasy-Abenteuer über die Reise zur Zerstörung des Einen Rings.',
                'genre' => 'Fantasy',
                'publication_year' => 1954,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/01_herr_der_ringe_die_gefaehrten.jpg'
            ],
            [
                'title' => 'Harry Potter und der Stein der Weisen',
                'author' => 'J.K. Rowling',
                'isbn' => '9783551551672',
                'description' => 'Der erste Band der magischen Harry Potter-Serie über den Jungen, der überlebte.',
                'genre' => 'Fantasy',
                'publication_year' => 1997,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 2,
                'image_path' => 'images/03_harry_potter_stein_der_weisen.jpg'
            ],
            [
                'title' => 'Das Lied von Eis und Feuer - Die Herren von Winterfell',
                'author' => 'George R.R. Martin',
                'isbn' => '9783442267743',
                'description' => 'Der Beginn der epischen Fantasy-Saga, die als Game of Thrones berühmt wurde.',
                'genre' => 'Fantasy',
                'publication_year' => 1996,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 3,
                'image_path' => 'images/05_das_lied_von_eis_und_feuer.jpg'
            ],
            [
                'title' => 'Der Name des Windes',
                'author' => 'Patrick Rothfuss',
                'isbn' => '9783608937152',
                'description' => 'Die Geschichte von Kvothe, einem legendären Helden und Magier.',
                'genre' => 'Fantasy',
                'publication_year' => 2007,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 4,
                'image_path' => 'images/22_der_name_des_windes_patrick_rothfuss.jpg'
            ],
            [
                'title' => 'Die Farbe der Magie',
                'author' => 'Terry Pratchett',
                'isbn' => '9783442209712',
                'description' => 'Humorvolle Fantasy-Satire auf der Scheibenwelt.',
                'genre' => 'Fantasy',
                'publication_year' => 1983,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 5,
                'image_path' => 'images/23_die_farbe_der_magie_terry_pratchett.jpg'
            ],
            [
                'title' => 'Eragon - Das Vermächtnis der Drachenreiter',
                'author' => 'Christopher Paolini',
                'isbn' => '9783570127742',
                'description' => 'Die Abenteuer eines jungen Drachenreiters in Alagaësia.',
                'genre' => 'Fantasy',
                'publication_year' => 2003,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 6,
                'image_path' => 'images/24_eragon_das_vermaechtnis_der_drachenreiter.jpg'
            ],
            [
                'title' => 'Der Hobbit',
                'author' => 'J.R.R. Tolkien',
                'isbn' => '9783423214124',
                'description' => 'Bilbo Beutlins unerwartete Reise zu den Einsamen Bergen.',
                'genre' => 'Fantasy',
                'publication_year' => 1937,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 7,
                'image_path' => 'images/25_der_hobbit_tolkien.jpg'
            ],
            [
                'title' => 'Die Klinge des Schicksals',
                'author' => 'Joe Abercrombie',
                'isbn' => '9783453533639',
                'description' => 'Dunkle Fantasy über Krieg, Verrat und Macht.',
                'genre' => 'Fantasy',
                'publication_year' => 2006,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 8,
                'image_path' => 'images/26_die_klinge_des_schicksals_joe_abercrombie.jpg'
            ],
            // ===== SCIENCE FICTION =====
            [
                'title' => 'Dune - Der Wüstenplanet',
                'author' => 'Frank Herbert',
                'isbn' => '9783453317840',
                'description' => 'Ein episches Science-Fiction-Meisterwerk über Politik, Religion und Ökologie.',
                'genre' => 'Science Fiction',
                'publication_year' => 1965,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/02_dune_der_wuestenplanet.jpg'
            ],
            [
                'title' => 'Foundation - Der Psychohistoriker',
                'author' => 'Isaac Asimov',
                'isbn' => '9783453528833',
                'description' => 'Ein Science-Fiction-Klassiker über die Vorhersage des Zerfalls eines galaktischen Imperiums.',
                'genre' => 'Science Fiction',
                'publication_year' => 1951,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 2,
                'image_path' => 'images/04_foundation_der_psychohistoriker.jpg'
            ],
            [
                'title' => 'Neuromancer',
                'author' => 'William Gibson',
                'isbn' => '9783453052116',
                'description' => 'Cyberpunk-Klassiker über Hacker und virtuelle Realitäten.',
                'genre' => 'Science Fiction',
                'publication_year' => 1984,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 3,
                'image_path' => 'images/27_neuromancer_william_gibson.jpg'
            ],
            [
                'title' => 'Blade Runner - Träumen Androiden von elektrischen Schafen?',
                'author' => 'Philip K. Dick',
                'isbn' => '9783453528840',
                'description' => 'Die Vorlage für den kultigen Film über Replikanten und Identität.',
                'genre' => 'Science Fiction',
                'publication_year' => 1968,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 4,
                'image_path' => 'images/28_blade_runner_philip_k_dick.jpg'
            ],
            [
                'title' => 'Der Marsianer',
                'author' => 'Andy Weir',
                'isbn' => '9783453315778',
                'description' => 'Ein Astronaut muss allein auf dem Mars überleben.',
                'genre' => 'Science Fiction',
                'publication_year' => 2011,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 5,
                'image_path' => 'images/29_der_marsianer_andy_weir.jpg'
            ],
            [
                'title' => 'Enders Spiel',
                'author' => 'Orson Scott Card',
                'isbn' => '9783453528857',
                'description' => 'Ein Kind wird zum militärischen Genie ausgebildet, um die Erde zu retten.',
                'genre' => 'Science Fiction',
                'publication_year' => 1985,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 6,
                'image_path' => 'images/30_enders_spiel_orson_scott_card.jpg'
            ],
            [
                'title' => 'Per Anhalter durch die Galaxis',
                'author' => 'Douglas Adams',
                'isbn' => '9783453146976',
                'description' => 'Humorvolle Science-Fiction über die Reise durch das Universum.',
                'genre' => 'Science Fiction',
                'publication_year' => 1979,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 7,
                'image_path' => 'images/31_per_anhalter_durch_die_galaxis_douglas_adams.jpg'
            ],
            // ===== KLASSIKER & LITERATUR =====
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'isbn' => '9783548234106',
                'description' => 'Ein dystopischer Roman über Überwachung und Kontrolle in einer totalitären Gesellschaft.',
                'genre' => 'Dystopie',
                'publication_year' => 1949,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/06_1984_george_orwell.jpg'
            ],
            [
                'title' => 'Stolz und Vorurteil',
                'author' => 'Jane Austen',
                'isbn' => '9783458177630',
                'description' => 'Ein klassischer Liebesroman über Elizabeth Bennet und Mr. Darcy.',
                'genre' => 'Klassiker',
                'publication_year' => 1813,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 2,
                'image_path' => 'images/07_stolz_und_vorurteil.jpg'
            ],
            [
                'title' => 'Die Verwandlung',
                'author' => 'Franz Kafka',
                'isbn' => '9783150090092',
                'description' => 'Eine surreale Erzählung über die Verwandlung eines Menschen in ein Ungeziefer.',
                'genre' => 'Klassiker',
                'publication_year' => 1915,
                'language' => 'deutsch',
                'condition' => 'befriedigend',
                'status' => 'verfügbar',
                'owner_id' => 3,
                'image_path' => 'images/08_die_verwandlung_kafka.jpg'
            ],
            [
                'title' => 'Der große Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'isbn' => '9783596901968',
                'description' => 'Ein Klassiker der amerikanischen Literatur über Träume und Enttäuschungen.',
                'genre' => 'Klassiker',
                'publication_year' => 1925,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 4,
                'image_path' => 'images/09_der_grosse_gatsby.jpg'
            ],
            [
                'title' => 'Wer die Nachtigall stört',
                'author' => 'Harper Lee',
                'isbn' => '9783499237522',
                'description' => 'Ein bewegender Roman über Rassismus und Moral im amerikanischen Süden.',
                'genre' => 'Klassiker',
                'publication_year' => 1960,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 5,
                'image_path' => 'images/32_wer_die_nachtigall_stoert_harper_lee.jpg'
            ],
            [
                'title' => 'Die Fänger im Roggen',
                'author' => 'J.D. Salinger',
                'isbn' => '9783499222610',
                'description' => 'Ein Klassiker über die Rebellion eines Teenagers gegen die Erwachsenenwelt.',
                'genre' => 'Klassiker',
                'publication_year' => 1951,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 6,
                'image_path' => 'images/33_die_faenger_im_roggen_salinger.jpg'
            ],
            [
                'title' => 'Brave New World',
                'author' => 'Aldous Huxley',
                'isbn' => '9783596905014',
                'description' => 'Eine Dystopie über eine kontrollierte Gesellschaft und den Verlust der Individualität.',
                'genre' => 'Dystopie',
                'publication_year' => 1932,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 7,
                'image_path' => 'images/34_brave_new_world_aldous_huxley.jpg'
            ],
            // ===== THRILLER & KRIMI =====
            [
                'title' => 'Gone Girl - Das perfekte Opfer',
                'author' => 'Gillian Flynn',
                'isbn' => '9783596196265',
                'description' => 'Ein psychologischer Thriller über eine Ehe, die in einem Alptraum endet.',
                'genre' => 'Thriller',
                'publication_year' => 2012,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/10_gone_girl_das_perfekte_opfer.jpg'
            ],
            [
                'title' => 'Der Schwarm',
                'author' => 'Frank Schätzing',
                'isbn' => '9783462034127',
                'description' => 'Ein Öko-Thriller über die Rache der Meere an der Menschheit.',
                'genre' => 'Thriller',
                'publication_year' => 2004,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 2,
                'image_path' => 'images/11_der_schwarm_frank_schaetzing.jpg'
            ],
            [
                'title' => 'Millennium - Verblendung',
                'author' => 'Stieg Larsson',
                'isbn' => '9783453265790',
                'description' => 'Der erste Band der Millennium-Trilogie über Lisbeth Salander und Mikael Blomkvist.',
                'genre' => 'Krimi',
                'publication_year' => 2005,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 3,
                'image_path' => 'images/12_millennium_verblendung_stieg_larsson.jpg'
            ],
            [
                'title' => 'The Silent Patient',
                'author' => 'Alex Michaelides',
                'isbn' => '9783746634838',
                'description' => 'Ein psychologischer Thriller über eine Frau, die nach einem Mord schweigt.',
                'genre' => 'Thriller',
                'publication_year' => 2019,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 4,
                'image_path' => 'images/35_the_silent_patient_alex_michaelides.jpg'
            ],
            [
                'title' => 'Shutter Island',
                'author' => 'Dennis Lehane',
                'isbn' => '9783548605937',
                'description' => 'Ein mysteriöser Thriller auf einer Insel mit einer psychiatrischen Anstalt.',
                'genre' => 'Thriller',
                'publication_year' => 2003,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 5,
                'image_path' => 'images/36_shutter_island_dennis_lehane.jpg'
            ],
            [
                'title' => 'Der Talentierte Mr. Ripley',
                'author' => 'Patricia Highsmith',
                'isbn' => '9783257229431',
                'description' => 'Psychologischer Thriller über einen charmanten Hochstapler.',
                'genre' => 'Thriller',
                'publication_year' => 1955,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 6,
            ],
            // ===== SACHBÜCHER =====
            [
                'title' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'isbn' => '9783826655487',
                'description' => 'Ein Handbuch für agile Software-Entwicklung und sauberen Code.',
                'genre' => 'Sachbuch',
                'publication_year' => 2008,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/13_clean_code_robert_martin.jpg'
            ],
            [
                'title' => 'Sapiens - Eine kurze Geschichte der Menschheit',
                'author' => 'Yuval Noah Harari',
                'isbn' => '9783570552698',
                'description' => 'Eine faszinierende Reise durch die Geschichte der Menschheit.',
                'genre' => 'Sachbuch',
                'publication_year' => 2011,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 2,
                'image_path' => 'images/14_sapiens_yuval_harari.jpg'
            ],
            [
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'isbn' => '9783442178582',
                'description' => 'Die transformative Kraft kleiner Gewohnheiten.',
                'genre' => 'Ratgeber',
                'publication_year' => 2018,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 3,
                'image_path' => 'images/15_atomic_habits_james_clear.jpg'
            ],
            [
                'title' => 'Thinking, Fast and Slow',
                'author' => 'Daniel Kahneman',
                'isbn' => '9783886808267',
                'description' => 'Einblicke in die Kognitionspsychologie und Entscheidungsfindung.',
                'genre' => 'Sachbuch',
                'publication_year' => 2011,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 4,
                'image_path' => 'images/39_thinking_fast_and_slow_daniel_kahneman.jpg'
            ],
            // ===== HUMOR & UNTERHALTUNG =====
            [
                'title' => 'Die Känguru-Chroniken',
                'author' => 'Marc-Uwe Kling',
                'isbn' => '9783548372594',
                'description' => 'Humorvolle Geschichten über das Leben mit einem kommunistischen Känguru.',
                'genre' => 'Humor',
                'publication_year' => 2009,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/16_kaenguru_chroniken_marc_uwe_kling.jpg'
            ],
            [
                'title' => 'Der Hundertjährige, der aus dem Fenster stieg',
                'author' => 'Jonas Jonasson',
                'isbn' => '9783442747672',
                'description' => 'Eine humorvolle Abenteuergeschichte über einen eigenwilligen Hundertjährigen.',
                'genre' => 'Humor',
                'publication_year' => 2009,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 2,
                'image_path' => 'images/17_der_hundertjaehrige_jonas_jonasson.jpg'
            ],
            [
                'title' => 'Tschick',
                'author' => 'Wolfgang Herrndorf',
                'isbn' => '9783499256356',
                'description' => 'Ein Coming-of-Age-Roman über zwei Jugendliche auf einem Road Trip.',
                'genre' => 'Jugendbuch',
                'publication_year' => 2010,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/18_tschick_wolfgang_herrndorf.jpg'
            ],
            [
                'title' => 'Qualityland',
                'author' => 'Marc-Uwe Kling',
                'isbn' => '9783550050367',
                'description' => 'Satirische Dystopie über eine perfekt optimierte Gesellschaft.',
                'genre' => 'Humor',
                'publication_year' => 2017,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 4,
            ],
            // ===== BIOGRAFIEN =====
            [
                'title' => 'Steve Jobs',
                'author' => 'Walter Isaacson',
                'isbn' => '9783570101926',
                'description' => 'Die autorisierte Biografie des Apple-Gründers.',
                'genre' => 'Biografie',
                'publication_year' => 2011,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/19_steve_jobs_walter_isaacson.jpg'
            ],
            [
                'title' => 'Becoming - Meine Geschichte',
                'author' => 'Michelle Obama',
                'isbn' => '9783442314225',
                'description' => 'Die Memoiren der ehemaligen First Lady der USA.',
                'genre' => 'Biografie',
                'publication_year' => 2018,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 2,
                'image_path' => 'images/20_becoming_michelle_obama.jpg'
            ],
            [
                'title' => 'Einstein - Sein Leben und sein Universum',
                'author' => 'Walter Isaacson',
                'isbn' => '9783570008003',
                'description' => 'Die umfassende Biografie des größten Physikers aller Zeiten.',
                'genre' => 'Biografie',
                'publication_year' => 2007,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 3,
            ],
            // ===== KOCHBÜCHER =====
            [
                'title' => 'Salt, Fat, Acid, Heat',
                'author' => 'Samin Nosrat',
                'isbn' => '9783831037643',
                'description' => 'Die vier Grundlagen guten Kochens.',
                'genre' => 'Kochbuch',
                'publication_year' => 2017,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/21_salt_fat_acid_heat_samin_nosrat.jpg'
            ],
            [
                'title' => 'Das perfekte Dinner',
                'author' => 'Gordon Ramsay',
                'isbn' => '9783831037681',
                'description' => 'Kochbuch mit Rezepten für besondere Anlässe vom Starkoch.',
                'genre' => 'Kochbuch',
                'publication_year' => 2019,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 2,
            ],
            // ===== HORROR =====
            [
                'title' => 'Es',
                'author' => 'Stephen King',
                'isbn' => '9783453435735',
                'description' => 'Horror-Klassiker über den Clown Pennywise und die Stadt Derry.',
                'genre' => 'Horror',
                'publication_year' => 1986,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/43_es_stephen_king.jpg'
            ],
            [
                'title' => 'Dracula',
                'author' => 'Bram Stoker',
                'isbn' => '9783150204085',
                'description' => 'Der klassische Vampir-Roman.',
                'genre' => 'Horror',
                'publication_year' => 1897,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 2,
                'image_path' => 'images/44_dracula_bram_stoker.jpg'
            ],
            // ===== ROMANCE =====
            [
                'title' => 'Me Before You',
                'author' => 'Jojo Moyes',
                'isbn' => '9783499267444',
                'description' => 'Eine bewegende Liebesgeschichte über Leben und Entscheidungen.',
                'genre' => 'Romance',
                'publication_year' => 2012,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/45_me_before_you_jojo_moyes.jpg'
            ],
            [
                'title' => 'Ein ganzes halbes Jahr',
                'author' => 'Jojo Moyes',
                'isbn' => '9783596196272',
                'description' => 'Die Fortsetzung der bewegenden Liebesgeschichte.',
                'genre' => 'Romance',
                'publication_year' => 2015,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 6,
            ],
            // ===== MYSTERY =====
            [
                'title' => 'Der Da Vinci Code',
                'author' => 'Dan Brown',
                'isbn' => '9783404148660',
                'description' => 'Ein Thriller über religiöse Symbole und Geheimnisse.',
                'genre' => 'Mystery',
                'publication_year' => 2003,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/47_der_da_vinci_code_dan_brown.jpg'
            ],
            [
                'title' => 'Mord im Orientexpress',
                'author' => 'Agatha Christie',
                'isbn' => '9783596901982',
                'description' => 'Klassischer Kriminalroman mit Hercule Poirot.',
                'genre' => 'Mystery',
                'publication_year' => 1934,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 8,
            ],
            // ===== HISTORISCHE ROMANE =====
            [
                'title' => 'Die Säulen der Erde',
                'author' => 'Ken Follett',
                'isbn' => '9783404117741',
                'description' => 'Ein epischer historischer Roman über den Bau einer Kathedrale im Mittelalter.',
                'genre' => 'Historischer Roman',
                'publication_year' => 1989,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
                'image_path' => 'images/49_die_saeulen_der_erde_ken_follett.jpg'
            ],
            [
                'title' => 'Die Wanderhure',
                'author' => 'Iny Lorentz',
                'isbn' => '9783426635117',
                'description' => 'Historischer Roman über eine Frau im mittelalterlichen Deutschland.',
                'genre' => 'Historischer Roman',
                'publication_year' => 2004,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 10,
            ],
            // ===== PHILOSOPHIE =====
            [
                'title' => 'Sophies Welt',
                'author' => 'Jostein Gaarder',
                'isbn' => '9783446177246',
                'description' => 'Roman über die Geschichte der Philosophie.',
                'genre' => 'Philosophie',
                'publication_year' => 1991,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 1,
            ],
            // ===== REISE & ABENTEUER =====
            [
                'title' => 'Eat, Pray, Love',
                'author' => 'Elizabeth Gilbert',
                'isbn' => '9783596512133',
                'description' => 'Autobiografischer Roman über Selbstfindung auf Reisen.',
                'genre' => 'Reise',
                'publication_year' => 2006,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 2,
            ],
            [
                'title' => 'Wild',
                'author' => 'Cheryl Strayed',
                'isbn' => '9783442158461',
                'description' => 'Memoir über eine 1700 km Wanderung als Therapie.',
                'genre' => 'Reise',
                'publication_year' => 2012,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 3,
            ],
            // ===== POLITIK & GESELLSCHAFT =====
            [
                'title' => '21 Lektionen für das 21. Jahrhundert',
                'author' => 'Yuval Noah Harari',
                'isbn' => '9783406727788',
                'description' => 'Analysen zu den großen Herausforderungen unserer Zeit.',
                'genre' => 'Sachbuch',
                'publication_year' => 2018,
                'language' => 'deutsch',
                'condition' => 'sehr gut',
                'status' => 'verfügbar',
                'owner_id' => 4,
            ],
            // ===== PSYCHOLOGIE =====
            [
                'title' => 'The 7 Habits of Highly Effective People',
                'author' => 'Stephen R. Covey',
                'isbn' => '9783897495456',
                'description' => 'Ratgeber für persönliche und berufliche Effektivität.',
                'genre' => 'Ratgeber',
                'publication_year' => 1989,
                'language' => 'deutsch',
                'condition' => 'gut',
                'status' => 'verfügbar',
                'owner_id' => 5,
            ],
        ];

        // Create books
        foreach ($books as $bookData) {
            Book::firstOrCreate(
                ['isbn' => $bookData['isbn']],
                $bookData
            );
        }
    }
}
